scheming_version: 2
schema_id: admin_panel_example_config
about: An example how to use scheming for config page

fields:
  - field_name: ckanext.ap_example.footer_html
    label: CKEditor 5
    form_snippet: wysiwyg_ckeditor5.html
    display_snippet: wysiwyg_ckeditor5.html

  - field_name: ckanext.ap_example.summernote
    label: Summernote
    form_snippet: wysiwyg_summernote.html
    display_snippet: wysiwyg_summernote.html

  - field_name: ckanext.ap_example.cache.duration
    label: Cache TTL
    form_placeholder: 600
    input_type: number

  - field_name: ckanext.ap_example.drupal_url
    label: Drupal base URL
    required: true
    display_snippet: link.html

  - field_name: ckanext.ap_example.api_version
    label: API version
    preset: select
    required: true
    choices:
      - value: json
        label: JSON API
      - value: core
        label: Core REST API

  - field_name: ckanext.ap_example.core.menu_export_endpoint
    label: Menu export API endpoint
    required: true
    help_text: If you are using the core API version, you might face the situation when your endpoint differ from the default one

  - field_name: ckanext.ap_example.timeout
    label: API request timeout
    input_type: number

  - field_name: ckanext.ap_example.request.user
    label: HTTP auth user

  - field_name: ckanext.ap_example.request.pass
    label: HTTP auth password
    input_type: password
