version: 1
groups:
  - annotation: ckanext-admin_panel
    options:
      - key: ckanext.admin_panel.show_toolbar_theme_switcher
        type: bool:
        description: Enable/disable theme switcher on a toolbar
        default: True
