scheming_version: 2
schema_id: ap_doi_config
about: Configuration options for the DOI extension

fields:
  - field_name: ckanext.ap_doi.mock_api_calls
    label: Mock API calls
    help_text: If enabled, the extension will not make any API calls to DataCite
    validators: default(true), one_of([true, false])
    preset: select
    required: true
    choices:
      - value: true
        label: Enabled
      - value: false
        label: Disabled

  - field_name: ckanext.doi.account_name
    label: Account name
    required: true
    help_text: Your DataCite Repository account
    form_snippet: text.html
    display_snippet: text.html

  - field_name: ckanext.doi.account_password
    label: Account password
    required: true
    help_text: Your DataCite Repository account password
    input_type: password

  - field_name: ckanext.doi.prefix
    label: DOI prefix
    required: true
    help_text: The prefix taken from your DataCite Repository account (from your test account if running in test mode)

  - field_name: ckanext.doi.publisher
    label: Publisher
    required: true
    help_text: The name of the institution publishing the DOI

  - field_name: ckanext.doi.test_mode
    label: Test mode
    required: true
    help_text: If test mode is set to true, the DOIs will use the DataCite test site. The test site uses a separate account, so you must also change your credentials and prefix.
    validators: default(true), one_of([true, false])
    preset: select
    required: true
    choices:
      - value: true
        label: Enabled
      - value: false
        label: Disabled

  - field_name: ckanext.doi.site_url
    label: Site URL
    help_text: Used to build the link back to the dataset

  - field_name: ckanext.doi.site_title
    label: Site title
    help_text: Site title to use in the citation
